services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6b!5fZ*!2%oy94Dz
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - ~/postgres_data:/var/lib/postgresql/data
    restart: always
